# Use the official Node.js image as the base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY frontend/package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the app's files
COPY frontend/ .

# Expose the port on which Next.js will run
EXPOSE 3000

# Start the Next.js app when the container starts
CMD ["npm", "run", "dev"]