version: '3.7'
services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000